// Generated by js_of_ocaml 3.5.2
(function(joo_global_object)
   {"use strict";
    function raw_array_sub(a,i,l)
     {var b=new Array(l);for(var j=0;j < l;j++)b[j] = a[i + j];return b}
    function caml_subarray_to_string(a,i,len)
     {var f=String.fromCharCode;
      if(i == 0 && len <= 4096 && len == a.length)return f.apply(null,a);
      var s="";
      for(;0 < len;i += 1024,len -= 1024)
       s += f.apply(null,raw_array_sub(a,i,Math.min(len,1024)));
      return s}
    function caml_convert_string_to_array(s)
     {if(joo_global_object.Uint8Array)
       var a=new (joo_global_object.Uint8Array)(s.l);
      else
       var a=new Array(s.l);
      var b=s.c,l=b.length,i=0;
      for(;i < l;i++)a[i] = b.charCodeAt(i);
      for(l = s.l;i < l;i++)a[i] = 0;
      s.c = a;
      s.t = 4;
      return a}
    function caml_blit_bytes(s1,i1,s2,i2,len)
     {if(len == 0)return 0;
      if(i2 == 0 && (len >= s2.l || s2.t == 2 && len >= s2.c.length))
       {s2.c
        =
        s1.t == 4
         ?caml_subarray_to_string(s1.c,i1,len)
         :i1 == 0 && s1.c.length == len?s1.c:s1.c.substr(i1,len);
        s2.t = s2.c.length == s2.l?0:2}
      else
       if(s2.t == 2 && i2 == s2.c.length)
        {s2.c
         +=
         s1.t == 4
          ?caml_subarray_to_string(s1.c,i1,len)
          :i1 == 0 && s1.c.length == len?s1.c:s1.c.substr(i1,len);
         s2.t = s2.c.length == s2.l?0:2}
       else
        {if(s2.t != 4)caml_convert_string_to_array(s2);
         var c1=s1.c,c2=s2.c;
         if(s1.t == 4)
          if(i2 <= i1)
           for(var i=0;i < len;i++)c2[i2 + i] = c1[i1 + i];
          else
           for(var i=len - 1;i >= 0;i--)c2[i2 + i] = c1[i1 + i];
         else
          {var l=Math.min(len,c1.length - i1);
           for(var i=0;i < l;i++)c2[i2 + i] = c1.charCodeAt(i1 + i);
           for(;i < len;i++)c2[i2 + i] = 0}}
      return 0}
    function caml_blit_string(s1,i1,s2,i2,len)
     {return caml_blit_bytes(s1,i1,s2,i2,len)}
    function raw_array_append_one(a,x)
     {var l=a.length,b=new Array(l + 1),i=0;
      for(;i < l;i++)b[i] = a[i];
      b[i] = x;
      return b}
    function caml_call_gen(f,args)
     {if(f.fun)return caml_call_gen(f.fun,args);
      var n=f.length,argsLen=args.length,d=n - argsLen;
      if(d == 0)
       return f.apply(null,args);
      else
       if(d < 0)
        return caml_call_gen
                (f.apply(null,raw_array_sub(args,0,n)),
                 raw_array_sub(args,n,argsLen - n));
       else
        return function(x)
         {return caml_call_gen(f,raw_array_append_one(args,x))}}
    function caml_str_repeat(n,s)
     {if(n == 0)return "";
      if(s.repeat)return s.repeat(n);
      var r="",l=0;
      if(n == 0)return r;
      for(;;)
       {if(n & 1)r += s;
        n >>= 1;
        if(n == 0)return r;
        s += s;
        l++;
        if(l == 9)s.slice(0,1)}}
    function caml_convert_string_to_bytes(s)
     {if(s.t == 2)
       s.c += caml_str_repeat(s.l - s.c.length,"\0");
      else
       s.c = caml_subarray_to_string(s.c,0,s.c.length);
      s.t = 0}
    function caml_is_ascii(s)
     {if(s.length < 24)
       {for(var i=0;i < s.length;i++)if(s.charCodeAt(i) > 127)return false;
        return true}
      else
       return ! /[^\x00-\x7f]/.test(s)}
    function caml_utf16_of_utf8(s)
     {for(var b="",t="",c,c1,c2,v,i=0,l=s.length;i < l;i++)
       {c1 = s.charCodeAt(i);
        if(c1 < 0x80)
         {for(var j=i + 1;j < l && (c1 = s.charCodeAt(j)) < 0x80;j++);
          if(j - i > 512)
           {t.substr(0,1);b += t;t = "";b += s.slice(i,j)}
          else
           t += s.slice(i,j);
          if(j == l)break;
          i = j}
        v = 1;
        if(++i < l && ((c2 = s.charCodeAt(i)) & - 64) == 128)
         {c = c2 + (c1 << 6);
          if(c1 < 0xe0)
           {v = c - 0x3080;if(v < 0x80)v = 1}
          else
           {v = 2;
            if(++i < l && ((c2 = s.charCodeAt(i)) & - 64) == 128)
             {c = c2 + (c << 6);
              if(c1 < 0xf0)
               {v = c - 0xe2080;
                if(v < 0x800 || v >= 0xd7ff && v < 0xe000)v = 2}
              else
               {v = 3;
                if
                 (++i
                  <
                  l
                  &&
                  ((c2 = s.charCodeAt(i)) & - 64)
                  ==
                  128
                  &&
                  c1
                  <
                  0xf5)
                 {v = c2 - 0x3c82080 + (c << 6);
                  if(v < 0x10000 || v > 0x10ffff)v = 3}}}}}
        if(v < 4)
         {i -= v;t += "\ufffd"}
        else
         if(v > 0xffff)
          t += String.fromCharCode(0xd7c0 + (v >> 10),0xdc00 + (v & 0x3FF));
         else
          t += String.fromCharCode(v);
        if(t.length > 1024){t.substr(0,1);b += t;t = ""}}
      return b + t}
    function caml_to_js_string(s)
     {switch(s.t)
       {case 9:return s.c;
        default:caml_convert_string_to_bytes(s);case 0:
         if(caml_is_ascii(s.c)){s.t = 9;return s.c}s.t = 8;
        case 8:return caml_utf16_of_utf8(s.c)
        }}
    function MlBytes(tag,contents,length)
     {this.t = tag;this.c = contents;this.l = length}
    MlBytes.prototype.toString = function(){return caml_to_js_string(this)};
    MlBytes.prototype.slice
    =
    function()
     {var content=this.t == 4?this.c.slice():this.c;
      return new MlBytes(this.t,content,this.l)};
    function caml_raise_with_arg(tag,arg){throw [0,tag,arg]}
    function caml_new_string(s){return new MlBytes(0,s,s.length)}
    function caml_raise_with_string(tag,msg)
     {caml_raise_with_arg(tag,caml_new_string(msg))}
    var caml_global_data=[0];
    function caml_invalid_argument(msg)
     {caml_raise_with_string(caml_global_data.Invalid_argument,msg)}
    function caml_create_bytes(len)
     {if(len < 0)caml_invalid_argument("Bytes.create");
      return new MlBytes(len?2:9,"",len)}
    function caml_fill_bytes(s,i,l,c)
     {if(l > 0)
       if(i == 0 && (l >= s.l || s.t == 2 && l >= s.c.length))
        if(c == 0)
         {s.c = "";s.t = 2}
        else
         {s.c = caml_str_repeat(l,String.fromCharCode(c));s.t = l == s.l?0:2}
       else
        {if(s.t != 4)caml_convert_string_to_array(s);
         for(l += i;i < l;i++)s.c[i] = c}
      return 0}
    var caml_oo_last_id=0;
    function caml_fresh_oo_id(){return caml_oo_last_id++}
    function caml_failwith(msg)
     {caml_raise_with_string(caml_global_data.Failure,msg)}
    if(joo_global_object.process && joo_global_object.process.cwd)
     var caml_current_dir=joo_global_object.process.cwd().replace(/\\/g,"/");
    else
     var caml_current_dir="/static";
    if(caml_current_dir.slice(- 1) !== "/")caml_current_dir += "/";
    function caml_make_path(name)
     {name = name instanceof MlBytes?name.toString():name;
      if(name.charCodeAt(0) != 47)name = caml_current_dir + name;
      var comp=name.split("/"),ncomp=[];
      for(var i=0;i < comp.length;i++)
       switch(comp[i])
        {case "..":if(ncomp.length > 1)ncomp.pop();break;
         case ".":break;
         case "":if(ncomp.length == 0)ncomp.push("");break;
         default:ncomp.push(comp[i]);break}
      ncomp.orig = name;
      return ncomp}
    function caml_raise_sys_error(msg)
     {caml_raise_with_string(caml_global_data.Sys_error,msg)}
    function caml_raise_no_such_file(name)
     {name = name instanceof MlBytes?name.toString():name;
      caml_raise_sys_error(name + ": No such file or directory")}
    function caml_string_of_array(a){return new MlBytes(4,a,a.length)}
    function caml_string_bound_error()
     {caml_invalid_argument("index out of bounds")}
    function caml_bytes_unsafe_get(s,i)
     {switch(s.t & 6)
       {default:if(i >= s.c.length)return 0;case 0:return s.c.charCodeAt(i);
        case 4:return s.c[i]
        }}
    function caml_bytes_get(s,i)
     {if(i >>> 0 >= s.l)caml_string_bound_error();
      return caml_bytes_unsafe_get(s,i)}
    function caml_ml_bytes_length(s){return s.l}
    function MlFile(){}
    function MlFakeFile(content){this.data = content}
    MlFakeFile.prototype = new MlFile();
    MlFakeFile.prototype.truncate
    =
    function(len)
     {var old=this.data;
      this.data = caml_create_bytes(len | 0);
      caml_blit_bytes(old,0,this.data,0,len)};
    MlFakeFile.prototype.length
    =
    function(){return caml_ml_bytes_length(this.data)};
    MlFakeFile.prototype.write
    =
    function(offset,buf,pos,len)
     {var clen=this.length();
      if(offset + len >= clen)
       {var new_str=caml_create_bytes(offset + len),old_data=this.data;
        this.data = new_str;
        caml_blit_bytes(old_data,0,this.data,0,clen)}
      caml_blit_bytes(buf,pos,this.data,offset,len);
      return 0};
    MlFakeFile.prototype.read
    =
    function(offset,buf,pos,len)
     {var clen=this.length();
      caml_blit_bytes(this.data,offset,buf,pos,len);
      return 0};
    MlFakeFile.prototype.read_one
    =
    function(offset){return caml_bytes_get(this.data,offset)};
    MlFakeFile.prototype.close = function(){};
    MlFakeFile.prototype.constructor = MlFakeFile;
    function MlFakeDevice(root,f)
     {this.content = {};this.root = root;this.lookupFun = f}
    MlFakeDevice.prototype.nm = function(name){return this.root + name};
    MlFakeDevice.prototype.lookup
    =
    function(name)
     {if(! this.content[name] && this.lookupFun)
       {var
         res=
          this.lookupFun(caml_new_string(this.root),caml_new_string(name));
        if(res !== 0)this.content[name] = new MlFakeFile(res[1])}};
    MlFakeDevice.prototype.exists
    =
    function(name)
     {if(name == "")return 1;
      var name_slash=name + "/",r=new RegExp("^" + name_slash);
      for(var n in this.content)if(n.match(r))return 1;
      this.lookup(name);
      return this.content[name]?1:0};
    MlFakeDevice.prototype.readdir
    =
    function(name)
     {var
       name_slash=name == ""?"":name + "/",
       r=new RegExp("^" + name_slash + "([^/]*)"),
       seen={},
       a=[];
      for(var n in this.content)
       {var m=n.match(r);
        if(m && ! seen[m[1]]){seen[m[1]] = true;a.push(m[1])}}
      return a};
    MlFakeDevice.prototype.is_dir
    =
    function(name)
     {var
       name_slash=name == ""?"":name + "/",
       r=new RegExp("^" + name_slash + "([^/]*)"),
       a=[];
      for(var n in this.content){var m=n.match(r);if(m)return 1}
      return 0};
    MlFakeDevice.prototype.unlink
    =
    function(name)
     {var ok=this.content[name]?true:false;
      delete this.content[name];
      return ok};
    MlFakeDevice.prototype.open
    =
    function(name,f)
     {if(f.rdonly && f.wronly)
       caml_raise_sys_error
        (this.nm(name)
         +
         " : flags Open_rdonly and Open_wronly are not compatible");
      if(f.text && f.binary)
       caml_raise_sys_error
        (this.nm(name)
         +
         " : flags Open_text and Open_binary are not compatible");
      this.lookup(name);
      if(this.content[name])
       {if(this.is_dir(name))
         caml_raise_sys_error(this.nm(name) + " : is a directory");
        if(f.create && f.excl)
         caml_raise_sys_error(this.nm(name) + " : file already exists");
        var file=this.content[name];
        if(f.truncate)file.truncate();
        return file}
      else
       if(f.create)
        {this.content[name] = new MlFakeFile(caml_create_bytes(0));
         return this.content[name]}
       else
        caml_raise_no_such_file(this.nm(name))};
    MlFakeDevice.prototype.register
    =
    function(name,content)
     {if(this.content[name])
       caml_raise_sys_error(this.nm(name) + " : file already exists");
      if(content instanceof MlBytes)
       this.content[name] = new MlFakeFile(content);
      else
       if(content instanceof Array)
        this.content[name] = new MlFakeFile(caml_string_of_array(content));
       else
        if(content.toString)
         {var mlstring=caml_new_string(content.toString());
          this.content[name] = new MlFakeFile(mlstring)}};
    MlFakeDevice.prototype.constructor = MlFakeDevice;
    function caml_array_of_string(s)
     {if(s.t != 4)caml_convert_string_to_array(s);return s.c}
    function caml_bytes_unsafe_set(s,i,c)
     {c &= 0xff;
      if(s.t != 4)
       {if(i == s.c.length)
         {s.c += String.fromCharCode(c);if(i + 1 == s.l)s.t = 0;return 0}
        caml_convert_string_to_array(s)}
      s.c[i] = c;
      return 0}
    function caml_bytes_set(s,i,c)
     {if(i >>> 0 >= s.l)caml_string_bound_error();
      return caml_bytes_unsafe_set(s,i,c)}
    var Buffer=joo_global_object.Buffer;
    function MlNodeFile(fd){this.fs = require("fs");this.fd = fd}
    MlNodeFile.prototype = new MlFile();
    MlNodeFile.prototype.truncate
    =
    function(len){this.fs.ftruncateSync(this.fd,len | 0)};
    MlNodeFile.prototype.length
    =
    function(){return this.fs.fstatSync(this.fd).size};
    MlNodeFile.prototype.write
    =
    function(offset,buf,buf_offset,len)
     {var a=caml_array_of_string(buf);
      if(! (a instanceof joo_global_object.Uint8Array))
       a = new (joo_global_object.Uint8Array)(a);
      var buffer=Buffer.from(a);
      this.fs.writeSync(this.fd,buffer,buf_offset,len,offset);
      return 0};
    MlNodeFile.prototype.read
    =
    function(offset,buf,buf_offset,len)
     {var a=caml_array_of_string(buf);
      if(! (a instanceof joo_global_object.Uint8Array))
       a = new (joo_global_object.Uint8Array)(a);
      var buffer=Buffer.from(a);
      this.fs.readSync(this.fd,buffer,buf_offset,len,offset);
      for(var i=0;i < len;i++)
       caml_bytes_set(buf,buf_offset + i,buffer[buf_offset + i]);
      return 0};
    MlNodeFile.prototype.read_one
    =
    function(offset)
     {var a=new (joo_global_object.Uint8Array)(1),buffer=Buffer.from(a);
      this.fs.readSync(this.fd,buffer,0,1,offset);
      return buffer[0]};
    MlNodeFile.prototype.close = function(){this.fs.closeSync(this.fd)};
    MlNodeFile.prototype.constructor = MlNodeFile;
    function MlNodeDevice(root){this.fs = require("fs");this.root = root}
    MlNodeDevice.prototype.nm = function(name){return this.root + name};
    MlNodeDevice.prototype.exists
    =
    function(name){return this.fs.existsSync(this.nm(name))?1:0};
    MlNodeDevice.prototype.readdir
    =
    function(name){return this.fs.readdirSync(this.nm(name))};
    MlNodeDevice.prototype.is_dir
    =
    function(name){return this.fs.statSync(this.nm(name)).isDirectory()?1:0};
    MlNodeDevice.prototype.unlink
    =
    function(name)
     {var b=this.fs.existsSync(this.nm(name))?1:0;
      this.fs.unlinkSync(this.nm(name));
      return b};
    MlNodeDevice.prototype.open
    =
    function(name,f)
     {var consts=require("constants"),res=0;
      for(var key in f)
       switch(key)
        {case "rdonly":res |= consts.O_RDONLY;break;
         case "wronly":res |= consts.O_WRONLY;break;
         case "append":res |= consts.O_WRONLY | consts.O_APPEND;break;
         case "create":res |= consts.O_CREAT;break;
         case "truncate":res |= consts.O_TRUNC;break;
         case "excl":res |= consts.O_EXCL;break;
         case "binary":res |= consts.O_BINARY;break;
         case "text":res |= consts.O_TEXT;break;
         case "nonblock":res |= consts.O_NONBLOCK;break
         }
      var fd=this.fs.openSync(this.nm(name),res);
      return new MlNodeFile(fd)};
    MlNodeDevice.prototype.rename
    =
    function(o,n){this.fs.renameSync(this.nm(o),this.nm(n))};
    MlNodeDevice.prototype.constructor = MlNodeDevice;
    var caml_root=caml_current_dir.match(/[^\/]*\//)[0];
    function fs_node_supported()
     {return typeof joo_global_object.process
             !==
             "undefined"
             &&
             typeof joo_global_object.process.versions
             !==
             "undefined"
             &&
             typeof joo_global_object.process.versions.node
             !==
             "undefined"
             &&
             joo_global_object.process.platform
             !==
             "browser"}
    var jsoo_mount_point=[];
    if(fs_node_supported())
     jsoo_mount_point.push
      ({path:caml_root,device:new MlNodeDevice(caml_root)});
    else
     jsoo_mount_point.push
      ({path:caml_root,device:new MlFakeDevice(caml_root)});
    jsoo_mount_point.push
     ({path:caml_root + "static/",
       device:new MlFakeDevice(caml_root + "static/")});
    function resolve_fs_device(name)
     {var
       path=caml_make_path(name),
       name=path.join("/"),
       name_slash=name + "/",
       res;
      for(var i=0;i < jsoo_mount_point.length;i++)
       {var m=jsoo_mount_point[i];
        if
         (name_slash.search(m.path)
          ==
          0
          &&
          (! res || res.path.length < m.path.length))
         res
         =
         {path:m.path,
          device:m.device,
          rest:name.substring(m.path.length,name.length)}}
      return res}
    function caml_create_file(name,content)
     {var root=resolve_fs_device(name);
      if(! root.device.register)caml_failwith("cannot register file");
      root.device.register(root.rest,content);
      return 0}
    function caml_fs_init()
     {var tmp=joo_global_object.caml_fs_tmp;
      if(tmp)
       for(var i=0;i < tmp.length;i++)
        caml_create_file(tmp[i].name,tmp[i].content);
      joo_global_object.caml_create_file = caml_create_file;
      joo_global_object.caml_fs_tmp = [];
      return 0}
    var log2_ok=Math.log2 && Math.log2(1.1235582092889474E+307) == 1020;
    function jsoo_floor_log2(x)
     {if(log2_ok)return Math.floor(Math.log2(x));
      var i=0;
      if(x == 0)return - Infinity;
      if(x >= 1)while(x >= 2){x /= 2;i++}else while(x < 1){x *= 2;i--}
      return i}
    function caml_int32_bits_of_float(x)
     {var float32a=new (joo_global_object.Float32Array)(1);
      float32a[0] = x;
      var int32a=new (joo_global_object.Int32Array)(float32a.buffer);
      return int32a[0] | 0}
    function caml_int64_create_lo_mi_hi(lo,mi,hi){return [255,lo,mi,hi]}
    function caml_int64_bits_of_float(x)
     {if(! isFinite(x))
       {if(isNaN(x))return caml_int64_create_lo_mi_hi(1,0,0x7ff0);
        return x > 0
                ?caml_int64_create_lo_mi_hi(0,0,0x7ff0)
                :caml_int64_create_lo_mi_hi(0,0,0xfff0)}
      var sign=x == 0 && 1 / x == - Infinity?0x8000:x >= 0?0:0x8000;
      if(sign)x = - x;
      var exp=jsoo_floor_log2(x) + 1023;
      if(exp <= 0)
       {exp = 0;x /= Math.pow(2,- 1026)}
      else
       {x /= Math.pow(2,exp - 1027);
        if(x < 16){x *= 2;exp -= 1}
        if(exp == 0)x /= 2}
      var k=Math.pow(2,24),r3=x | 0;
      x = (x - r3) * k;
      var r2=x | 0;
      x = (x - r2) * k;
      var r1=x | 0;
      r3 = r3 & 0xf | sign | exp << 4;
      return caml_int64_create_lo_mi_hi(r1,r2,r3)}
    function caml_int64_to_bytes(x)
     {return [x[3] >> 8,
              x[3] & 0xff,
              x[2] >> 16,
              x[2] >> 8 & 0xff,
              x[2] & 0xff,
              x[1] >> 16,
              x[1] >> 8 & 0xff,
              x[1] & 0xff]}
    function caml_ba_serialize(writer,ba,sz)
     {writer.write(32,ba.dims.length);
      writer.write(32,ba.kind | ba.layout << 8);
      for(var i=0;i < ba.dims.length;i++)writer.write(32,ba.dims[i]);
      switch(ba.kind)
       {case 2:
        case 3:
        case 12:
         for(var i=0;i < ba.data.length;i++)writer.write(8,ba.data[i]);break;
        case 4:
        case 5:
         for(var i=0;i < ba.data.length;i++)writer.write(16,ba.data[i]);break;
        case 6:
         for(var i=0;i < ba.data.length;i++)writer.write(32,ba.data[i]);break;
        case 8:
        case 9:
         writer.write(8,0);
         for(var i=0;i < ba.data.length;i++)writer.write(32,ba.data[i]);
         break;
        case 7:
         for(var i=0;i < ba.data.length / 2;i++)
          {var b=caml_int64_to_bytes(ba.get(i));
           for(var j=0;j < 8;j++)writer.write(8,b[j])}
         break;
        case 1:
         for(var i=0;i < ba.data.length;i++)
          {var b=caml_int64_to_bytes(caml_int64_bits_of_float(ba.get(i)));
           for(var j=0;j < 8;j++)writer.write(8,b[j])}
         break;
        case 0:
         for(var i=0;i < ba.data.length;i++)
          {var b=caml_int32_bits_of_float(ba.get(i));writer.write(32,b)}
         break;
        case 10:
         for(var i=0;i < ba.data.length / 2;i++)
          {var j=ba.get(i);
           writer.write(32,caml_int32_bits_of_float(j[1]));
           writer.write(32,caml_int32_bits_of_float(j[2]))}
         break;
        case 11:
         for(var i=0;i < ba.data.length / 2;i++)
          {var
            complex=ba.get(i),
            b=caml_int64_to_bytes(caml_int64_bits_of_float(complex[1]));
           for(var j=0;j < 8;j++)writer.write(8,b[j]);
           var b=caml_int64_to_bytes(caml_int64_bits_of_float(complex[2]));
           for(var j=0;j < 8;j++)writer.write(8,b[j])}
         break
        }
      sz[0] = (4 + ba.dims.length) * 4;
      sz[1] = (4 + ba.dims.length) * 8}
    function caml_ba_get_size_per_element(kind)
     {switch(kind){case 7:case 10:case 11:return 2;default:return 1}}
    function caml_ba_create_buffer(kind,size)
     {var g=joo_global_object,view;
      switch(kind)
       {case 0:view = g.Float32Array;break;
        case 1:view = g.Float64Array;break;
        case 2:view = g.Int8Array;break;
        case 3:view = g.Uint8Array;break;
        case 4:view = g.Int16Array;break;
        case 5:view = g.Uint16Array;break;
        case 6:view = g.Int32Array;break;
        case 7:view = g.Int32Array;break;
        case 8:view = g.Int32Array;break;
        case 9:view = g.Int32Array;break;
        case 10:view = g.Float32Array;break;
        case 11:view = g.Float64Array;break;
        case 12:view = g.Uint8Array;break
        }
      if(! view)caml_invalid_argument("Bigarray.create: unsupported kind");
      var data=new view(size * caml_ba_get_size_per_element(kind));
      return data}
    function caml_int32_float_of_bits(x)
     {var int32a=new (joo_global_object.Int32Array)(1);
      int32a[0] = x;
      var float32a=new (joo_global_object.Float32Array)(int32a.buffer);
      return float32a[0]}
    function caml_int64_of_bytes(a)
     {return [255,
              a[7] | a[6] << 8 | a[5] << 16,
              a[4] | a[3] << 8 | a[2] << 16,
              a[1] | a[0] << 8]}
    function caml_int64_float_of_bits(x)
     {var lo=x[1],mi=x[2],hi=x[3],exp=(hi & 0x7fff) >> 4;
      if(exp == 2047)
       return (lo | mi | hi & 0xf) == 0?hi & 0x8000?- Infinity:Infinity:NaN;
      var k=Math.pow(2,- 24),res=(lo * k + mi) * k + (hi & 0xf);
      if(exp > 0)
       {res += 16;res *= Math.pow(2,exp - 1027)}
      else
       res *= Math.pow(2,- 1026);
      if(hi & 0x8000)res = - res;
      return res}
    function caml_ba_get_size(dims)
     {var n_dims=dims.length,size=1;
      for(var i=0;i < n_dims;i++)
       {if(dims[i] < 0)
         caml_invalid_argument("Bigarray.create: negative dimension");
        size = size * dims[i]}
      return size}
    function caml_int64_create_lo_hi(lo,hi)
     {return [255,
              lo & 0xffffff,
              lo >>> 24 & 0xff | (hi & 0xffff) << 8,
              hi >>> 16 & 0xffff]}
    function caml_int64_hi32(v){return v[2] >>> 8 & 0xffff | v[3] << 16}
    function caml_int64_lo32(v){return v[1] | (v[2] & 0xff) << 24}
    function caml_array_bound_error()
     {caml_invalid_argument("index out of bounds")}
    function Ml_Bigarray(kind,layout,dims,buffer)
     {this.kind = kind;
      this.layout = layout;
      this.dims = dims;
      this.data = buffer}
    Ml_Bigarray.prototype.caml_custom = "_bigarray";
    Ml_Bigarray.prototype.offset
    =
    function(arg)
     {var ofs=0;
      if(typeof arg === "number")arg = [arg];
      if(! (arg instanceof Array))
       caml_invalid_argument("bigarray.js: invalid offset");
      if(this.dims.length != arg.length)
       caml_invalid_argument("Bigarray.get/set: bad number of dimensions");
      if(this.layout == 0)
       for(var i=0;i < this.dims.length;i++)
        {if(arg[i] < 0 || arg[i] >= this.dims[i])caml_array_bound_error();
         ofs = ofs * this.dims[i] + arg[i]}
      else
       for(var i=this.dims.length - 1;i >= 0;i--)
        {if(arg[i] < 1 || arg[i] > this.dims[i])caml_array_bound_error();
         ofs = ofs * this.dims[i] + (arg[i] - 1)}
      return ofs};
    Ml_Bigarray.prototype.get
    =
    function(ofs)
     {switch(this.kind)
       {case 7:
         var l=this.data[ofs * 2 + 0],h=this.data[ofs * 2 + 1];
         return caml_int64_create_lo_hi(l,h);
        case 10:
        case 11:
         var r=this.data[ofs * 2 + 0],i=this.data[ofs * 2 + 1];
         return [254,r,i];
        default:return this.data[ofs]}};
    Ml_Bigarray.prototype.set
    =
    function(ofs,v)
     {switch(this.kind)
       {case 7:
         this.data[ofs * 2 + 0] = caml_int64_lo32(v);
         this.data[ofs * 2 + 1] = caml_int64_hi32(v);
         break;
        case 10:
        case 11:
         this.data[ofs * 2 + 0] = v[1];this.data[ofs * 2 + 1] = v[2];break;
        default:this.data[ofs] = v;break}
      return 0};
    Ml_Bigarray.prototype.fill
    =
    function(v)
     {switch(this.kind)
       {case 7:
         var a=caml_int64_lo32(v),b=caml_int64_hi32(v);
         if(a == b)
          this.data.fill(a);
         else
          for(var i=0;i < this.data.length;i++)this.data[i] = i % 2 == 0?a:b;
         break;
        case 10:
        case 11:
         var im=v[1],re=v[2];
         if(im == re)
          this.data.fill(im);
         else
          for(var i=0;i < this.data.length;i++)
           this.data[i] = i % 2 == 0?im:re;
         break;
        default:this.data.fill(v);break}};
    Ml_Bigarray.prototype.compare
    =
    function(b,total)
     {if(this.layout != b.layout || this.kind != b.kind)
       {var k1=this.kind | this.layout << 8,k2=b.kind | b.layout << 8;
        return k2 - k1}
      if(this.dims.length != b.dims.length)
       return b.dims.length - this.dims.length;
      for(var i=0;i < this.dims.length;i++)
       if(this.dims[i] != b.dims[i])return this.dims[i] < b.dims[i]?- 1:1;
      switch(this.kind)
       {case 0:
        case 1:
        case 10:
        case 11:
         var x,y;
         for(var i=0;i < this.data.length;i++)
          {x = this.data[i];
           y = b.data[i];
           if(x < y)return - 1;
           if(x > y)return 1;
           if(x != y)
            {if(! total)return NaN;if(x == x)return 1;if(y == y)return - 1}}
         break;
        case 7:
         for(var i=0;i < this.data.length;i += 2)
          {if(this.data[i + 1] < b.data[i + 1])return - 1;
           if(this.data[i + 1] > b.data[i + 1])return 1;
           if(this.data[i] >>> 0 < b.data[i] >>> 0)return - 1;
           if(this.data[i] >>> 0 > b.data[i] >>> 0)return 1}
         break;
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 8:
        case 9:
        case 12:
         for(var i=0;i < this.data.length;i++)
          {if(this.data[i] < b.data[i])return - 1;
           if(this.data[i] > b.data[i])return 1}
         break
        }
      return 0};
    function Ml_Bigarray_c_1_1(kind,layout,dims,buffer)
     {this.kind = kind;
      this.layout = layout;
      this.dims = dims;
      this.data = buffer}
    Ml_Bigarray_c_1_1.prototype = new Ml_Bigarray();
    Ml_Bigarray_c_1_1.prototype.offset
    =
    function(arg)
     {if(typeof arg !== "number")
       if(arg instanceof Array && arg.length == 1)
        arg = arg[0];
       else
        caml_invalid_argument("Ml_Bigarray_c_1_1.offset");
      if(arg < 0 || arg >= this.dims[0])caml_array_bound_error();
      return arg};
    Ml_Bigarray_c_1_1.prototype.get = function(ofs){return this.data[ofs]};
    Ml_Bigarray_c_1_1.prototype.set
    =
    function(ofs,v){this.data[ofs] = v;return 0};
    Ml_Bigarray_c_1_1.prototype.fill
    =
    function(v){this.data.fill(v);return 0};
    function caml_ba_create_unsafe(kind,layout,dims,data)
     {var size_per_element=caml_ba_get_size_per_element(kind);
      if(caml_ba_get_size(dims) * size_per_element != data.length)
       caml_invalid_argument("length doesn't match dims");
      if(layout == 0 && dims.length == 1 && size_per_element == 1)
       return new Ml_Bigarray_c_1_1(kind,layout,dims,data);
      return new Ml_Bigarray(kind,layout,dims,data)}
    function caml_ba_deserialize(reader,sz)
     {var num_dims=reader.read32s();
      if(num_dims < 0 || num_dims > 16)
       caml_failwith("input_value: wrong number of bigarray dimensions");
      var tag=reader.read32s(),kind=tag & 0xff,layout=tag >> 8 & 1,dims=[];
      for(var i=0;i < num_dims;i++)dims.push(reader.read32u());
      var
       size=caml_ba_get_size(dims),
       data=caml_ba_create_buffer(kind,size),
       ba=caml_ba_create_unsafe(kind,layout,dims,data);
      switch(kind)
       {case 2:for(var i=0;i < size;i++)data[i] = reader.read8s();break;
        case 3:
        case 12:for(var i=0;i < size;i++)data[i] = reader.read8u();break;
        case 4:for(var i=0;i < size;i++)data[i] = reader.read16s();break;
        case 5:for(var i=0;i < size;i++)data[i] = reader.read16u();break;
        case 6:for(var i=0;i < size;i++)data[i] = reader.read32s();break;
        case 8:
        case 9:
         var sixty=reader.read8u();
         if(sixty)
          caml_failwith
           ("input_value: cannot read bigarray with 64-bit OCaml ints");
         for(var i=0;i < size;i++)data[i] = reader.read32s();
         break;
        case 7:
         var t=new Array(8);
         for(var i=0;i < size;i++)
          {for(var j=0;j < 8;j++)t[j] = reader.read8u();
           var int64=caml_int64_of_bytes(t);
           ba.set(i,int64)}
         break;
        case 1:
         var t=new Array(8);
         for(var i=0;i < size;i++)
          {for(var j=0;j < 8;j++)t[j] = reader.read8u();
           var f=caml_int64_float_of_bits(caml_int64_of_bytes(t));
           ba.set(i,f)}
         break;
        case 0:
         for(var i=0;i < size;i++)
          {var f=caml_int32_float_of_bits(reader.read32s());ba.set(i,f)}
         break;
        case 10:
         for(var i=0;i < size;i++)
          {var
            re=caml_int32_float_of_bits(reader.read32s()),
            im=caml_int32_float_of_bits(reader.read32s());
           ba.set(i,[254,re,im])}
         break;
        case 11:
         var t=new Array(8);
         for(var i=0;i < size;i++)
          {for(var j=0;j < 8;j++)t[j] = reader.read8u();
           var re=caml_int64_float_of_bits(caml_int64_of_bytes(t));
           for(var j=0;j < 8;j++)t[j] = reader.read8u();
           var im=caml_int64_float_of_bits(caml_int64_of_bytes(t));
           ba.set(i,[254,re,im])}
         break
        }
      sz[0] = (4 + num_dims) * 4;
      return caml_ba_create_unsafe(kind,layout,dims,data)}
    function caml_ba_compare(a,b,total){return a.compare(b,total)}
    if(! Math.imul)
     Math.imul
     =
     function(x,y){y |= 0;return ((x >> 16) * y << 16) + (x & 0xffff) * y | 0};
    var caml_mul=Math.imul;
    function caml_hash_mix_int(h,d)
     {d = caml_mul(d,0xcc9e2d51 | 0);
      d = d << 15 | d >>> 32 - 15;
      d = caml_mul(d,0x1b873593);
      h ^= d;
      h = h << 13 | h >>> 32 - 13;
      return (h + (h << 2) | 0) + (0xe6546b64 | 0) | 0}
    function caml_hash_mix_int64(h,v)
     {h = caml_hash_mix_int(h,caml_int64_lo32(v));
      h = caml_hash_mix_int(h,caml_int64_hi32(v));
      return h}
    function caml_hash_mix_float(h,v0)
     {return caml_hash_mix_int64(h,caml_int64_bits_of_float(v0))}
    function caml_ba_hash(ba)
     {var num_elts=caml_ba_get_size(ba.dims),h=0;
      switch(ba.kind)
       {case 2:
        case 3:
        case 12:
         if(num_elts > 256)num_elts = 256;
         var w=0,i=0;
         for(i = 0;i + 4 <= ba.data.length;i += 4)
          {w
           =
           ba.data[i + 0]
           |
           ba.data[i + 1]
           <<
           8
           |
           ba.data[i + 2]
           <<
           16
           |
           ba.data[i + 3]
           <<
           24;
           h = caml_hash_mix_int(h,w)}
         w = 0;
         switch(num_elts & 3)
          {case 3:w = ba.data[i + 2] << 16;
           case 2:w |= ba.data[i + 1] << 8;
           case 1:w |= ba.data[i + 0];h = caml_hash_mix_int(h,w)
           }
         break;
        case 4:
        case 5:
         if(num_elts > 128)num_elts = 128;
         var w=0,i=0;
         for(i = 0;i + 2 <= ba.data.length;i += 2)
          {w = ba.data[i + 0] | ba.data[i + 1] << 16;
           h = caml_hash_mix_int(h,w)}
         if((num_elts & 1) != 0)h = caml_hash_mix_int(h,ba.data[i]);
         break;
        case 6:
         if(num_elts > 64)num_elts = 64;
         for(var i=0;i < num_elts;i++)h = caml_hash_mix_int(h,ba.data[i]);
         break;
        case 8:
        case 9:
         if(num_elts > 64)num_elts = 64;
         for(var i=0;i < num_elts;i++)h = caml_hash_mix_int(h,ba.data[i]);
         break;
        case 7:
         if(num_elts > 32)num_elts = 32;
         num_elts *= 2;
         for(var i=0;i < num_elts;i++)h = caml_hash_mix_int(h,ba.data[i]);
         break;
        case 10:num_elts *= 2;
        case 0:
         if(num_elts > 64)num_elts = 64;
         for(var i=0;i < num_elts;i++)h = caml_hash_mix_float(h,ba.data[i]);
         break;
        case 11:num_elts *= 2;
        case 1:
         if(num_elts > 32)num_elts = 32;
         for(var i=0;i < num_elts;i++)h = caml_hash_mix_float(h,ba.data[i]);
         break
        }
      return h}
    function caml_int32_unmarshal(reader,size)
     {size[0] = 4;return reader.read32s()}
    function caml_nativeint_unmarshal(reader,size)
     {switch(reader.read8u())
       {case 1:size[0] = 4;return reader.read32s();
        case 2:caml_failwith("input_value: native integer value too large");
        default:caml_failwith("input_value: ill-formed native integer")}}
    function caml_int64_unmarshal(reader,size)
     {var t=new Array(8);
      for(var j=0;j < 8;j++)t[j] = reader.read8u();
      size[0] = 8;
      return caml_int64_of_bytes(t)}
    function caml_int64_marshal(writer,v,sizes)
     {var b=caml_int64_to_bytes(v);
      for(var i=0;i < 8;i++)writer.write(8,b[i]);
      sizes[0] = 8;
      sizes[1] = 8}
    function caml_int64_compare(x,y)
     {var x3=x[3] << 16,y3=y[3] << 16;
      if(x3 > y3)return 1;
      if(x3 < y3)return - 1;
      if(x[2] > y[2])return 1;
      if(x[2] < y[2])return - 1;
      if(x[1] > y[1])return 1;
      if(x[1] < y[1])return - 1;
      return 0}
    function caml_int64_hash(x)
     {var lo=x[1] | (x[2] & 0xff) << 24,hi=x[2] >>> 8 & 0xffff | x[3] << 16;
      return lo ^ hi}
    var
     caml_custom_ops=
      {"_j":
       {deserialize:caml_int64_unmarshal,
        serialize:caml_int64_marshal,
        fixed_length:8,
        compare:caml_int64_compare,
        hash:caml_int64_hash},
       "_i":{deserialize:caml_int32_unmarshal,fixed_length:4},
       "_n":{deserialize:caml_nativeint_unmarshal,fixed_length:4},
       "_bigarray":
       {deserialize:caml_ba_deserialize,
        serialize:caml_ba_serialize,
        compare:caml_ba_compare,
        hash:caml_ba_hash}};
    function caml_compare_val_get_custom(a)
     {return caml_custom_ops[a.caml_custom]
             &&
             caml_custom_ops[a.caml_custom].compare}
    function caml_compare_val_number_custom(num,custom,swap,total)
     {var comp=caml_compare_val_get_custom(custom);
      if(comp)
       {var x=swap > 0?comp(custom,num,total):comp(num,custom,total);
        if(total && x != x)return swap;
        if(+ x != + x)return + x;
        if((x | 0) != 0)return x | 0}
      return swap}
    function caml_compare_val_tag(a)
     {if(typeof a === "number")
       return 1000;
      else
       if(a instanceof MlBytes)
        return 252;
       else
        if(a instanceof Array && a[0] === a[0] >>> 0 && a[0] <= 255)
         {var tag=a[0] | 0;return tag == 254?0:tag}
        else
         if(a instanceof String)
          return 1252;
         else
          if(typeof a == "string")
           return 1252;
          else
           if(a instanceof Number)
            return 1000;
           else
            if(a && a.caml_custom)
             return 1255;
            else
             if(a && a.compare)
              return 1256;
             else
              if(typeof a == "function")
               return 1247;
              else
               if(typeof a == "symbol")return 1251;
      return 1001}
    function caml_int_compare(a,b)
     {if(a < b)return - 1;if(a == b)return 0;return 1}
    function caml_string_compare(s1,s2)
     {s1.t & 6 && caml_convert_string_to_bytes(s1);
      s2.t & 6 && caml_convert_string_to_bytes(s2);
      return s1.c < s2.c?- 1:s1.c > s2.c?1:0}
    function caml_compare_val(a,b,total)
     {var stack=[];
      for(;;)
       {if(! (total && a === b))
         {var tag_a=caml_compare_val_tag(a);
          if(tag_a == 250){a = a[1];continue}
          var tag_b=caml_compare_val_tag(b);
          if(tag_b == 250){b = b[1];continue}
          if(tag_a !== tag_b)
           {if(tag_a == 1000)
             {if(tag_b == 1255)
               return caml_compare_val_number_custom(a,b,- 1,total);
              return - 1}
            if(tag_b == 1000)
             {if(tag_a == 1255)
               return caml_compare_val_number_custom(b,a,1,total);
              return 1}
            return tag_a < tag_b?- 1:1}
          switch(tag_a)
           {case 247:caml_invalid_argument("compare: functional value");break;
            case 248:
             var x=caml_int_compare(a[2],b[2]);if(x != 0)return x | 0;break;
            case 249:caml_invalid_argument("compare: functional value");break;
            case 250:
             caml_invalid_argument
              ("equal: got Forward_tag, should not happen");
             break;
            case 251:caml_invalid_argument("equal: abstract value");break;
            case 252:
             if(a !== b)
              {var x=caml_string_compare(a,b);if(x != 0)return x | 0}
             break;
            case 253:
             caml_invalid_argument("equal: got Double_tag, should not happen");
             break;
            case 254:
             caml_invalid_argument
              ("equal: got Double_array_tag, should not happen");
             break;
            case 255:
             var x=caml_int64_compare(a,b);if(x != 0)return x | 0;break;
            case 1247:
             caml_invalid_argument("compare: functional value");break;
            case 1255:
             var comp=caml_compare_val_get_custom(a);
             if(comp != caml_compare_val_get_custom(b))
              return a.caml_custom < b.caml_custom?- 1:1;
             if(! comp)caml_invalid_argument("compare: abstract value");
             var x=comp(a,b,total);
             if(x != x)return total?- 1:x;
             if(x !== (x | 0))return - 1;
             if(x != 0)return x | 0;
             break;
            case 1256:
             var x=a.compare(b,total);
             if(x != x)return total?- 1:x;
             if(x !== (x | 0))return - 1;
             if(x != 0)return x | 0;
             break;
            case 1000:
             a = + a;
             b = + b;
             if(a < b)return - 1;
             if(a > b)return 1;
             if(a != b)
              {if(! total)return NaN;if(a == a)return 1;if(b == b)return - 1}
             break;
            case 1001:
             if(a < b)return - 1;
             if(a > b)return 1;
             if(a != b)
              {if(! total)return NaN;if(a == a)return 1;if(b == b)return - 1}
             break;
            case 1251:if(a !== b){if(! total)return NaN;return 1}break;
            case 1252:
             var a=a.toString(),b=b.toString();
             if(a !== b){if(a < b)return - 1;if(a > b)return 1}
             break;
            case 246:
            case 254:
            default:
             if(a.length != b.length)return a.length < b.length?- 1:1;
             if(a.length > 1)stack.push(a,b,1);
             break}}
        if(stack.length == 0)return 0;
        var i=stack.pop();
        b = stack.pop();
        a = stack.pop();
        if(i + 1 < a.length)stack.push(a,b,i + 1);
        a = a[i];
        b = b[i]}}
    function caml_greaterequal(x,y)
     {return + (caml_compare_val(x,y,false) >= 0)}
    function caml_js_get_console()
     {var
       c=joo_global_object.console?joo_global_object.console:{},
       m=
        ["log",
         "debug",
         "info",
         "warn",
         "error",
         "assert",
         "dir",
         "dirxml",
         "trace",
         "group",
         "groupCollapsed",
         "groupEnd",
         "time",
         "timeEnd"];
      function f(){}
      for(var i=0;i < m.length;i++)if(! c[m[i]])c[m[i]] = f;
      return c}
    var caml_js_regexps={amp:/&/g,lt:/</g,quot:/\"/g,all:/[&<\"]/};
    function caml_js_html_escape(s)
     {if(! caml_js_regexps.all.test(s))return s;
      return s.replace(caml_js_regexps.amp,"&amp;").replace
               (caml_js_regexps.lt,"&lt;").replace
              (caml_js_regexps.quot,"&quot;")}
    function caml_utf8_of_utf16(s)
     {for(var b="",t=b,c,d,i=0,l=s.length;i < l;i++)
       {c = s.charCodeAt(i);
        if(c < 0x80)
         {for(var j=i + 1;j < l && (c = s.charCodeAt(j)) < 0x80;j++);
          if(j - i > 512)
           {t.substr(0,1);b += t;t = "";b += s.slice(i,j)}
          else
           t += s.slice(i,j);
          if(j == l)break;
          i = j}
        if(c < 0x800)
         {t += String.fromCharCode(0xc0 | c >> 6);
          t += String.fromCharCode(0x80 | c & 0x3f)}
        else
         if(c < 0xd800 || c >= 0xdfff)
          t
          +=
          String.fromCharCode
           (0xe0 | c >> 12,0x80 | c >> 6 & 0x3f,0x80 | c & 0x3f);
         else
          if
           (c
            >=
            0xdbff
            ||
            i
            +
            1
            ==
            l
            ||
            (d = s.charCodeAt(i + 1))
            <
            0xdc00
            ||
            d
            >
            0xdfff)
           t += "\xef\xbf\xbd";
          else
           {i++;
            c = (c << 10) + d - 0x35fdc00;
            t
            +=
            String.fromCharCode
             (0xf0 | c >> 18,
              0x80 | c >> 12 & 0x3f,
              0x80 | c >> 6 & 0x3f,
              0x80 | c & 0x3f)}
        if(t.length > 1024){t.substr(0,1);b += t;t = ""}}
      return b + t}
    function caml_js_to_string(s)
     {var tag=9;
      if(! caml_is_ascii(s))tag = 8,s = caml_utf8_of_utf16(s);
      return new MlBytes(tag,s,s.length)}
    function caml_js_wrap_callback(f)
     {return function()
       {return arguments.length > 0
                ?caml_call_gen(f,arguments)
                :caml_call_gen(f,[undefined])}}
    function caml_lessequal(x,y){return + (caml_compare_val(x,y,false) <= 0)}
    function caml_lessthan(x,y){return + (caml_compare_val(x,y,false) < 0)}
    var caml_ml_channels=new Array();
    function caml_ml_flush(chanid)
     {var chan=caml_ml_channels[chanid];
      if(! chan.opened)caml_raise_sys_error("Cannot flush a closed channel");
      if(! chan.buffer || chan.buffer == "")return 0;
      if
       (chan.fd
        &&
        caml_global_data.fds[chan.fd]
        &&
        caml_global_data.fds[chan.fd].output)
       {var output=caml_global_data.fds[chan.fd].output;
        switch(output.length)
         {case 2:output(chanid,chan.buffer);break;default:output(chan.buffer)}}
      chan.buffer = "";
      return 0}
    function caml_ml_string_length(s){return s.l}
    function caml_std_output(chanid,s)
     {var
       chan=caml_ml_channels[chanid],
       str=caml_new_string(s),
       slen=caml_ml_string_length(str);
      chan.file.write(chan.offset,str,0,slen);
      chan.offset += slen;
      return 0}
    function js_print_stderr(s)
     {var s=caml_utf16_of_utf8(s),g=joo_global_object;
      if(g.process && g.process.stdout && g.process.stdout.write)
       g.process.stderr.write(s);
      else
       {if(s.charCodeAt(s.length - 1) == 10)s = s.substr(0,s.length - 1);
        var v=g.console;
        v && v.error && v.error(s)}}
    function js_print_stdout(s)
     {var s=caml_utf16_of_utf8(s),g=joo_global_object;
      if(g.process && g.process.stdout && g.process.stdout.write)
       g.process.stdout.write(s);
      else
       {if(s.charCodeAt(s.length - 1) == 10)s = s.substr(0,s.length - 1);
        var v=g.console;
        v && v.log && v.log(s)}}
    function caml_sys_open_internal(idx,output,file,flags)
     {if(caml_global_data.fds === undefined)
       caml_global_data.fds = new Array();
      flags = flags?flags:{};
      var info={};
      info.file = file;
      info.offset = flags.append?file.length():0;
      info.flags = flags;
      info.output = output;
      caml_global_data.fds[idx] = info;
      if(! caml_global_data.fd_last_idx || idx > caml_global_data.fd_last_idx)
       caml_global_data.fd_last_idx = idx;
      return idx}
    function caml_sys_open(name,flags,_perms)
     {var f={};
      while(flags)
       {switch(flags[1])
         {case 0:f.rdonly = 1;break;
          case 1:f.wronly = 1;break;
          case 2:f.append = 1;break;
          case 3:f.create = 1;break;
          case 4:f.truncate = 1;break;
          case 5:f.excl = 1;break;
          case 6:f.binary = 1;break;
          case 7:f.text = 1;break;
          case 8:f.nonblock = 1;break
          }
        flags = flags[2]}
      if(f.rdonly && f.wronly)
       caml_raise_sys_error
        (name.toString()
         +
         " : flags Open_rdonly and Open_wronly are not compatible");
      if(f.text && f.binary)
       caml_raise_sys_error
        (name.toString()
         +
         " : flags Open_text and Open_binary are not compatible");
      var
       root=resolve_fs_device(name),
       file=root.device.open(root.rest,f),
       idx=caml_global_data.fd_last_idx?caml_global_data.fd_last_idx:0;
      return caml_sys_open_internal(idx + 1,caml_std_output,file,f)}
    caml_sys_open_internal
     (0,caml_std_output,new MlFakeFile(caml_create_bytes(0)));
    caml_sys_open_internal
     (1,js_print_stdout,new MlFakeFile(caml_create_bytes(0)));
    caml_sys_open_internal
     (2,js_print_stderr,new MlFakeFile(caml_create_bytes(0)));
    function caml_ml_open_descriptor_in(fd)
     {var data=caml_global_data.fds[fd];
      if(data.flags.wronly)caml_raise_sys_error("fd " + fd + " is writeonly");
      var
       channel=
        {file:data.file,
         offset:data.offset,
         fd:fd,
         opened:true,
         out:false,
         refill:null};
      caml_ml_channels[channel.fd] = channel;
      return channel.fd}
    function caml_ml_open_descriptor_out(fd)
     {var data=caml_global_data.fds[fd];
      if(data.flags.rdonly)caml_raise_sys_error("fd " + fd + " is readonly");
      var
       channel=
        {file:data.file,
         offset:data.offset,
         fd:fd,
         opened:true,
         out:true,
         buffer:""};
      caml_ml_channels[channel.fd] = channel;
      return channel.fd}
    function caml_ml_out_channels_list()
     {var l=0;
      for(var c=0;c < caml_ml_channels.length;c++)
       if
        (caml_ml_channels[c]
         &&
         caml_ml_channels[c].opened
         &&
         caml_ml_channels[c].out)
        l = [0,caml_ml_channels[c].fd,l];
      return l}
    function caml_jsbytes_of_string(s)
     {if((s.t & 6) != 0)caml_convert_string_to_bytes(s);return s.c}
    function caml_ml_output_bytes(chanid,buffer,offset,len)
     {var chan=caml_ml_channels[chanid];
      if(! chan.opened)
       caml_raise_sys_error("Cannot output to a closed channel");
      var string;
      if(offset == 0 && caml_ml_bytes_length(buffer) == len)
       string = buffer;
      else
       {string = caml_create_bytes(len);
        caml_blit_bytes(buffer,offset,string,0,len)}
      var
       jsstring=caml_jsbytes_of_string(string),
       id=jsstring.lastIndexOf("\n");
      if(id < 0)
       chan.buffer += jsstring;
      else
       {chan.buffer += jsstring.substr(0,id + 1);
        caml_ml_flush(chanid);
        chan.buffer += jsstring.substr(id + 1)}
      return 0}
    function caml_ml_output(chanid,buffer,offset,len)
     {return caml_ml_output_bytes(chanid,buffer,offset,len)}
    function caml_obj_tag(x)
     {if(x instanceof Array && x[0] == x[0] >>> 0)
       return x[0];
      else
       if(x instanceof MlBytes)
        return 252;
       else
        if(x instanceof Function || typeof x == "function")
         return 247;
        else
         if(x && x.caml_custom)return 255;else return 1000}
    function caml_register_global(n,v,name_opt)
     {if(name_opt && joo_global_object.toplevelReloc)
       n = joo_global_object.toplevelReloc(name_opt);
      caml_global_data[n + 1] = v;
      if(name_opt)caml_global_data[name_opt] = v}
    var caml_named_values={};
    function caml_register_named_value(nm,v)
     {caml_named_values[caml_jsbytes_of_string(nm)] = v;return 0}
    function caml_string_of_bytes(s){return s}
    function caml_sys_const_backend_type()
     {return [0,caml_new_string("js_of_ocaml")]}
    function caml_sys_const_max_wosize(){return 0x7FFFFFFF / 4 | 0}
    var
     caml_argv=
      function()
        {var g=joo_global_object,main="a.out",args=[];
         if(g.process && g.process.argv && g.process.argv.length > 1)
          {var argv=g.process.argv;
           main = argv[1];
           args = raw_array_sub(argv,2,argv.length - 2)}
         var p=caml_js_to_string(main),args2=[0,p];
         for(var i=0;i < args.length;i++)
          args2.push(caml_js_to_string(args[i]));
         return args2}
       ();
    function caml_sys_get_argv(a){return [0,caml_argv[1],caml_argv]}
    function caml_return_exn_constant(tag){return tag}
    function caml_named_value(nm){return caml_named_values[nm]}
    function caml_wrap_exception(e)
     {if(e instanceof Array)return e;
      if
       (joo_global_object.RangeError
        &&
        e instanceof joo_global_object.RangeError
        &&
        e.message
        &&
        e.message.match(/maximum call stack/i))
       return caml_return_exn_constant(caml_global_data.Stack_overflow);
      if
       (joo_global_object.InternalError
        &&
        e instanceof joo_global_object.InternalError
        &&
        e.message
        &&
        e.message.match(/too much recursion/i))
       return caml_return_exn_constant(caml_global_data.Stack_overflow);
      if(e instanceof joo_global_object.Error && caml_named_value("jsError"))
       return [0,caml_named_value("jsError"),e];
      return [0,caml_global_data.Failure,caml_js_to_string(String(e))]}
    function caml_call1(f,a0)
     {return f.length == 1?f(a0):caml_call_gen(f,[a0])}
    function caml_call3(f,a0,a1,a2)
     {return f.length == 3?f(a0,a1,a2):caml_call_gen(f,[a0,a1,a2])}
    caml_fs_init();
    var
     Out_of_memory=[248,caml_new_string("Out_of_memory"),-1],
     Sys_error=[248,caml_new_string("Sys_error"),-2],
     Failure=[248,caml_new_string("Failure"),-3],
     Invalid_argument=[248,caml_new_string("Invalid_argument"),-4],
     End_of_file=[248,caml_new_string("End_of_file"),-5],
     Division_by_zero=[248,caml_new_string("Division_by_zero"),-6],
     Not_found=[248,caml_new_string("Not_found"),-7],
     Match_failure=[248,caml_new_string("Match_failure"),-8],
     Stack_overflow=[248,caml_new_string("Stack_overflow"),-9],
     Sys_blocked_io=[248,caml_new_string("Sys_blocked_io"),-10],
     Assert_failure=[248,caml_new_string("Assert_failure"),-11],
     Undefined_recursive_module=
      [248,caml_new_string("Undefined_recursive_module"),-12];
    caml_register_global
     (11,Undefined_recursive_module,"Undefined_recursive_module");
    caml_register_global(10,Assert_failure,"Assert_failure");
    caml_register_global(9,Sys_blocked_io,"Sys_blocked_io");
    caml_register_global(8,Stack_overflow,"Stack_overflow");
    caml_register_global(7,Match_failure,"Match_failure");
    caml_register_global(6,Not_found,"Not_found");
    caml_register_global(5,Division_by_zero,"Division_by_zero");
    caml_register_global(4,End_of_file,"End_of_file");
    caml_register_global(3,Invalid_argument,"Invalid_argument");
    caml_register_global(2,Failure,"Failure");
    caml_register_global(1,Sys_error,"Sys_error");
    caml_register_global(0,Out_of_memory,"Out_of_memory");
    var
     _f_=caml_new_string("output_substring"),
     _o_=caml_new_string("String.blit / Bytes.blit_string"),
     _n_=caml_new_string("Bytes.blit"),
     _s_=caml_new_string(""),
     _q_=caml_new_string("String.concat"),
     _x_=caml_new_string("Buffer.add_substring/add_subbytes"),
     _w_=caml_new_string("Buffer.add: cannot grow buffer"),
     _ac_=[3,0,3],
     _ad_=caml_new_string("."),
     ___=caml_new_string(">"),
     _$_=caml_new_string("<\/"),
     _X_=caml_new_string(">"),
     _Y_=caml_new_string("<"),
     _U_=caml_new_string("\n"),
     _B_=caml_new_string("Stdlib.Format.Empty_queue"),
     _Q_=[0,caml_new_string("")],
     _ao_=caml_new_string("Js_of_ocaml__Js.Error"),
     _az_=caml_new_string("button"),
     _aM_=caml_new_string(":"),
     _aL_=caml_new_string("}"),
     _aN_=caml_new_string(","),
     _aO_=caml_new_string("{"),
     _aP_=caml_new_string("cannot parse json "),
     _aI_=caml_new_string('"'),
     _aJ_=caml_new_string('"'),
     _aE_=caml_new_string(": "),
     _aF_=caml_new_string("; "),
     _aG_=caml_new_string("style"),
     _aS_=caml_new_string("color is "),
     _aR_=caml_new_string("color"),
     _aT_=caml_new_string("click"),
     _aU_=caml_new_string("background-color"),
     _aQ_=
      [0,
       caml_new_string("#3aa757"),
       [0,
        caml_new_string("#e8453c"),
        [0,caml_new_string("#f9bb2d"),[0,caml_new_string("#4688f1"),0]]]];
    function _a_(_eS_){throw [0,Invalid_argument,_eS_]}
    caml_fresh_oo_id(0);
    var _b_=2147483647;
    function _c_(_eO_,_eN_)
     {var
       _eP_=caml_ml_string_length(_eO_),
       _eQ_=caml_ml_string_length(_eN_),
       _eR_=caml_create_bytes(_eP_ + _eQ_ | 0);
      caml_blit_string(_eO_,0,_eR_,0,_eP_);
      caml_blit_string(_eN_,0,_eR_,_eP_,_eQ_);
      return caml_string_of_bytes(_eR_)}
    caml_ml_open_descriptor_in(0);
    var
     _d_=caml_ml_open_descriptor_out(1),
     _e_=caml_ml_open_descriptor_out(2),
     _g_=
      [0,
       function(_eF_)
        {function _eG_(_eH_)
          {var _eI_=_eH_;
           for(;;)
            {if(_eI_)
              {var _eJ_=_eI_[2],_eK_=_eI_[1];
               try
                {caml_ml_flush(_eK_)}
               catch(_eM_)
                {_eM_ = caml_wrap_exception(_eM_);
                 if(_eM_[1] !== Sys_error)throw _eM_;
                 var _eL_=_eM_}
               var _eI_=_eJ_;
               continue}
             return 0}}
         return _eG_(caml_ml_out_channels_list(0))}];
    caml_sys_get_argv(0);
    var _j_=(4 * caml_sys_const_max_wosize(0) | 0) - 1 | 0;
    caml_fresh_oo_id(0);
    typeof caml_sys_const_backend_type(0) === "number";
    function _k_(_eC_,_eB_)
     {if(_eB_)
       {var _eD_=_eB_[2],_eE_=caml_call1(_eC_,_eB_[1]);
        return [0,_eE_,_k_(_eC_,_eD_)]}
      return 0}
    function _l_(_ey_,_ex_)
     {var _ez_=_ex_;
      for(;;)
       {if(_ez_)
         {var _eA_=_ez_[2];caml_call1(_ey_,_ez_[1]);var _ez_=_eA_;continue}
        return 0}}
    function _r_(_es_,_er_)
     {if(_er_)
       {var _et_=caml_ml_string_length(_es_),_ei_=0,_eh_=_er_,_eu_=0;
        for(;;)
         {if(_eh_)
           {var _ej_=_eh_[2],_ek_=_eh_[1];
            if(_ej_)
             {var
               _el_=(caml_ml_string_length(_ek_) + _et_ | 0) + _ei_ | 0,
               _em_=_ei_ <= _el_?_el_:_a_(_q_),
               _ei_=_em_,
               _eh_=_ej_;
              continue}
            var _ev_=caml_ml_string_length(_ek_) + _ei_ | 0}
          else
           var _ev_=_ei_;
          var _ew_=caml_create_bytes(_ev_),_eo_=_eu_,_en_=_er_;
          for(;;)
           {if(_en_)
             {var _ep_=_en_[2],_eq_=_en_[1];
              if(_ep_)
               {caml_blit_string(_eq_,0,_ew_,_eo_,caml_ml_string_length(_eq_));
                caml_blit_string
                 (_es_,0,_ew_,_eo_ + caml_ml_string_length(_eq_) | 0,_et_);
                var
                 _eo_=(_eo_ + caml_ml_string_length(_eq_) | 0) + _et_ | 0,
                 _en_=_ep_;
                continue}
              caml_blit_string(_eq_,0,_ew_,_eo_,caml_ml_string_length(_eq_))}
            return caml_string_of_bytes(_ew_)}}}
      return _s_}
    caml_fresh_oo_id(0);
    caml_fresh_oo_id(0);
    var _y_=[0,0];
    function _z_(_eg_){_y_[1] = [0,_eg_,_y_[1]];return 0}
    function _A_(_ed_,_ec_)
     {var _ee_=[0,_ed_,0],_ef_=_ec_[1];
      return _ef_
              ?(_ec_[1] = _ee_,_ef_[2] = _ee_,0)
              :(_ec_[1] = _ee_,_ec_[2] = _ee_,0)}
    var _C_=[248,_B_,caml_fresh_oo_id(0)];
    function _D_(_d__)
     {var _d$_=_d__[2];
      if(_d$_)
       {var _eb_=_d$_[2],_ea_=_d$_[1];
        _d__[2] = _eb_;
        if(0 === _eb_)_d__[1] = 0;
        return _ea_}
      throw _C_}
    function _E_(_d9_,_d8_)
     {_d9_[13] = _d9_[13] + _d8_[3] | 0;return _A_(_d8_,_d9_[28])}
    var _F_=1000000010;
    function _G_(_d7_,_d6_)
     {return caml_call3(_d7_[17],_d6_,0,caml_ml_string_length(_d6_))}
    function _H_(_d5_){return caml_call1(_d5_[19],0)}
    function _I_(_d1_,_d0_,_dZ_)
     {_H_(_d1_);
      _d1_[11] = 1;
      var
       _d2_=(_d1_[6] - _dZ_ | 0) + _d0_ | 0,
       _d3_=_d1_[8],
       _d4_=caml_lessequal(_d3_,_d2_)?_d3_:_d2_;
      _d1_[10] = _d4_;
      _d1_[9] = _d1_[6] - _d1_[10] | 0;
      return caml_call1(_d1_[21],_d1_[10])}
    function _J_(_dY_,_dX_){return _I_(_dY_,0,_dX_)}
    function _K_(_dW_,_dV_)
     {_dW_[9] = _dW_[9] - _dV_ | 0;return caml_call1(_dW_[20],_dV_)}
    function _L_(_dO_)
     {var _dP_=_dO_[2];
      if(_dP_)
       {var _dQ_=_dP_[1],_dR_=_dQ_[2],_dS_=_dQ_[1],_dT_=_dO_[9] < _dR_?1:0;
        if(_dT_)
         {if(0 !== _dS_)return 5 <= _dS_?0:_J_(_dO_,_dR_);var _dU_=0}
        else
         var _dU_=_dT_;
        return _dU_}
      return _H_(_dO_)}
    function _M_(_dL_)
     {var _dM_=_D_(_dL_[28]),_dN_=_dM_[1];
      _dL_[12] = _dL_[12] - _dM_[3] | 0;
      _dL_[9] = _dL_[9] + _dN_ | 0;
      return 0}
    function _N_(_c6_,_c5_,_c4_)
     {if(typeof _c4_ === "number")
       switch(_c4_)
        {case 0:
          var _c7_=_c6_[3];
          if(_c7_)
           {var
             _c8_=_c7_[1][1],
             _c9_=
              function(_dC_,_dB_)
               {if(_dB_)
                 {var _dE_=_dB_[1],_dD_=_dB_[2];
                  return caml_lessthan(_dC_,_dE_)
                          ?[0,_dC_,_dB_]
                          :[0,_dE_,_c9_(_dC_,_dD_)]}
                return [0,_dC_,0]};
            _c8_[1] = _c9_(_c6_[6] - _c6_[9] | 0,_c8_[1]);
            return 0}
          return 0;
         case 1:var _c__=_c6_[2];return _c__?(_c6_[2] = _c__[2],0):0;
         case 2:var _c$_=_c6_[3];return _c$_?(_c6_[3] = _c$_[2],0):0;
         case 3:var _da_=_c6_[2];return _da_?_J_(_c6_,_da_[1][2]):_H_(_c6_);
         case 4:
          var _db_=_c6_[10] !== (_c6_[6] - _c6_[9] | 0)?1:0;
          return _db_?_M_(_c6_):_db_;
         default:
          var _dc_=_c6_[5];
          if(_dc_)
           {var _dd_=_dc_[2];
            _G_(_c6_,caml_call1(_c6_[25],_dc_[1]));
            _c6_[5] = _dd_;
            return 0}
          return 0}
      else
       switch(_c4_[0])
        {case 0:
          var _de_=_c4_[1];
          _c6_[9] = _c6_[9] - _c5_ | 0;
          _G_(_c6_,_de_);
          _c6_[11] = 0;
          return 0;
         case 1:
          var _df_=_c4_[2],_dg_=_c4_[1],_dh_=_c6_[2];
          if(_dh_)
           {var _di_=_dh_[1],_dj_=_di_[2];
            switch(_di_[1])
             {case 0:return _K_(_c6_,_dg_);
              case 1:return _I_(_c6_,_df_,_dj_);
              case 2:return _I_(_c6_,_df_,_dj_);
              case 3:return _c6_[9] < _c5_?_I_(_c6_,_df_,_dj_):_K_(_c6_,_dg_);
              case 4:
               return _c6_[11]
                       ?_K_(_c6_,_dg_)
                       :_c6_[9] < _c5_
                         ?_I_(_c6_,_df_,_dj_)
                         :((_c6_[6] - _dj_ | 0) + _df_ | 0) < _c6_[10]
                           ?_I_(_c6_,_df_,_dj_)
                           :_K_(_c6_,_dg_);
              default:return _K_(_c6_,_dg_)}}
          return 0;
         case 2:
          var
           _dm_=_c6_[6] - _c6_[9] | 0,
           _dn_=_c6_[3],
           _dk_=_c4_[2],
           _dl_=_c4_[1];
          if(_dn_)
           {var
             _do_=_dn_[1][1],
             _dp_=
              function(_dH_,_dG_)
               {var _dI_=_dG_;
                for(;;)
                 {if(_dI_)
                   {var _dK_=_dI_[1],_dJ_=_dI_[2];
                    if(caml_greaterequal(_dK_,_dH_))return _dK_;
                    var _dI_=_dJ_;
                    continue}
                  throw Not_found}},
             _dq_=_do_[1];
            if(_dq_)
             {var _dr_=_dq_[1];
              try
               {var _dv_=_dp_(_dm_,_do_[1]),_ds_=_dv_}
              catch(_dF_)
               {_dF_ = caml_wrap_exception(_dF_);
                if(_dF_ !== Not_found)throw _dF_;
                var _ds_=_dr_}
              var _dt_=_ds_}
            else
             var _dt_=_dm_;
            var _du_=_dt_ - _dm_ | 0;
            return 0 <= _du_
                    ?_K_(_c6_,_du_ + _dl_ | 0)
                    :_I_(_c6_,_dt_ + _dk_ | 0,_c6_[6])}
          return 0;
         case 3:
          var _dw_=_c4_[2],_dx_=_c4_[1];
          if(_c6_[8] < (_c6_[6] - _c6_[9] | 0))_L_(_c6_);
          var _dy_=_c6_[9] - _dx_ | 0,_dz_=1 === _dw_?1:_c6_[9] < _c5_?_dw_:5;
          _c6_[2] = [0,[0,_dz_,_dy_],_c6_[2]];
          return 0;
         case 4:_c6_[3] = [0,_c4_[1],_c6_[3]];return 0;
         default:
          var _dA_=_c4_[1];
          _G_(_c6_,caml_call1(_c6_[24],_dA_));
          _c6_[5] = [0,_dA_,_c6_[5]];
          return 0}}
    function _O_(_cW_)
     {for(;;)
       {var _cU_=_cW_[28][2];
        if(_cU_)
         {var
           _cV_=_cU_[1],
           _cX_=_cV_[1],
           _c0_=_cX_ < 0?1:0,
           _cY_=_cV_[3],
           _cZ_=_cV_[2],
           _c1_=_c0_?(_cW_[13] - _cW_[12] | 0) < _cW_[9]?1:0:_c0_,
           _c2_=1 - _c1_;
          if(_c2_)
           {_D_(_cW_[28]);
            var _c3_=0 <= _cX_?_cX_:_F_;
            _N_(_cW_,_c3_,_cZ_);
            _cW_[12] = _cY_ + _cW_[12] | 0;
            continue}
          return _c2_}
        throw _C_}}
    function _P_(_cR_)
     {try
       {var _cS_=_O_(_cR_);return _cS_}
      catch(_cT_)
       {_cT_ = caml_wrap_exception(_cT_);if(_cT_ === _C_)return 0;throw _cT_}}
    var _R_=[0,[0,-1,[0,-1,_Q_,0]],0];
    function _S_(_cQ_){_cQ_[1] = _R_;return 0}
    function _T_(_cG_,_cF_)
     {var _cH_=_cG_[1];
      if(_cH_)
       {var _cI_=_cH_[1],_cJ_=_cI_[2],_cK_=_cJ_[1],_cL_=_cH_[2],_cM_=_cJ_[2];
        if(_cI_[1] < _cG_[12])return _S_(_cG_);
        if(typeof _cM_ !== "number")
         switch(_cM_[0])
          {case 3:
            var
             _cO_=1 - _cF_,
             _cP_=_cO_?(_cJ_[1] = _cG_[13] + _cK_ | 0,_cG_[1] = _cL_,0):_cO_;
            return _cP_;
           case 1:
           case 2:
            var
             _cN_=
              _cF_?(_cJ_[1] = _cG_[13] + _cK_ | 0,_cG_[1] = _cL_,0):_cF_;
            return _cN_
           }
        return 0}
      return 0}
    var _m_=caml_create_bytes(80);
    caml_fill_bytes(_m_,0,80,32);
    var _p_=caml_string_of_bytes(_m_);
    function _V_(_cC_,_cB_)
     {var _cD_=_cB_;
      for(;;)
       {var _cE_=0 < _cD_?1:0;
        if(_cE_)
         {if(80 < _cD_)
           {caml_call3(_cC_[17],_p_,0,80);var _cD_=_cD_ - 80 | 0;continue}
          return caml_call3(_cC_[17],_p_,0,_cD_)}
        return _cE_}}
    function _W_(_cA_){return _c_(_Y_,_c_(_cA_,_X_))}
    function _Z_(_cz_){return _c_(_$_,_c_(_cz_,___))}
    function _aa_(_cy_){return 0}
    function _ab_(_cx_){return 0}
    function _ae_(_cn_,_cm_)
     {function _co_(_cw_){return 0}
      function _cp_(_cv_){return 0}
      var _cj_=[0,0,0],_ck_=[0,-1,_ac_,0];
      function _cq_(_cu_){return 0}
      _A_(_ck_,_cj_);
      var
       _cl_=
        [0,
         [0,[0,1,_ck_],_R_],
         0,
         0,
         0,
         0,
         78,
         10,
         68,
         78,
         0,
         1,
         1,
         1,
         1,
         _b_,
         _ad_,
         _cn_,
         _cm_,
         _cq_,
         _cp_,
         _co_,
         0,
         0,
         _W_,
         _Z_,
         _aa_,
         _ab_,
         _cj_];
      _cl_[19] = function(_ct_){return caml_call3(_cl_[17],_U_,0,1)};
      _cl_[20] = function(_cs_){return _V_(_cl_,_cs_)};
      _cl_[21] = function(_cr_){return _V_(_cl_,_cr_)};
      return _cl_}
    function _af_(_cd_)
     {function _ce_(_ci_){return caml_ml_flush(_cd_)}
      return _ae_
              (function(_cf_,_cg_,_ch_)
                {if(0 <= _cg_)
                  if(0 <= _ch_)
                   if(! ((caml_ml_string_length(_cf_) - _ch_ | 0) < _cg_))
                    return caml_ml_output(_cd_,_cf_,_cg_,_ch_);
                 return _a_(_f_)},
               _ce_)}
    var
     _ah_=512,
     _t_=_j_ < 512?_j_:_ah_,
     _u_=caml_create_bytes(_t_),
     _v_=[0,_u_,0,_t_,_u_],
     _ai_=_af_(_d_);
    _af_(_e_);
    function _ag_(_cc_){return 0}
    _ae_
     (function(_b$_,_ca_,_cb_)
       {var _b5_=_ca_ < 0?1:0;
        if(_b5_)
         var _b6_=_b5_;
        else
         var
          _b__=_cb_ < 0?1:0,
          _b6_=_b__ || ((caml_ml_string_length(_b$_) - _cb_ | 0) < _ca_?1:0);
        if(_b6_)_a_(_x_);
        var _b7_=_v_[2] + _cb_ | 0;
        if(_v_[3] < _b7_)
         {var _b1_=[0,_v_[3]];
          for(;;)
           {if(_b1_[1] < (_v_[2] + _cb_ | 0))
             {_b1_[1] = 2 * _b1_[1] | 0;continue}
            if(_j_ < _b1_[1])
             {if(! ((_v_[2] + _cb_ | 0) <= _j_))throw [0,Failure,_w_];
              _b1_[1] = _j_}
            var
             _b2_=caml_create_bytes(_b1_[1]),
             _b3_=_v_[2],
             _b4_=_v_[1],
             switch$0=
              0 <= _b3_
               ?(caml_ml_bytes_length(_b4_) - _b3_ | 0) < 0
                 ?0
                 :(caml_ml_bytes_length(_b2_) - _b3_ | 0) < 0
                   ?0
                   :(caml_blit_bytes(_b4_,0,_b2_,0,_b3_),1)
               :0;
            if(! switch$0)_a_(_n_);
            _v_[1] = _b2_;
            _v_[3] = _b1_[1];
            break}}
        var
         _b8_=_v_[2],
         _b9_=_v_[1],
         switch$1=
          0 <= _cb_
           ?0 <= _ca_
             ?(caml_ml_string_length(_b$_) - _cb_ | 0) < _ca_
               ?0
               :0 <= _b8_
                 ?(caml_ml_bytes_length(_b9_) - _cb_ | 0) < _b8_
                   ?0
                   :(caml_blit_string(_b$_,_ca_,_b9_,_b8_,_cb_),1)
                 :0
             :0
           :0;
        if(! switch$1)_a_(_o_);
        _v_[2] = _b7_;
        return 0},
      _ag_);
    var _i_=[0,0],_h_=_g_[1];
    _g_[1]
    =
    function(_bO_)
     {if(1 - _i_[1])
       {_i_[1] = 1;
        var _bV_=_ai_[4];
        _l_
         (function(_b0_)
           {if(_ai_[23])_E_(_ai_,[0,0,5,0]);
            var _bW_=_ai_[22];
            if(_bW_)
             {var _bX_=_ai_[4];
              if(_bX_)
               {var _bY_=_bX_[2];
                caml_call1(_ai_[27],_bX_[1]);
                _ai_[4] = _bY_;
                return 0}
              var _bZ_=0}
            else
             var _bZ_=_bW_;
            return _bZ_},
          _bV_);
        for(;;)
         {if(1 < _ai_[14])
           {if(1 < _ai_[14])
             {if(_ai_[14] < _ai_[15])
               {_E_(_ai_,[0,0,1,0]);_T_(_ai_,1);_T_(_ai_,0)}
              _ai_[14] = _ai_[14] - 1 | 0}
            continue}
          _ai_[13] = _F_;
          _P_(_ai_);
          _ai_[12] = 1;
          _ai_[13] = 1;
          var _bP_=_ai_[28];
          _bP_[1] = 0;
          _bP_[2] = 0;
          _S_(_ai_);
          _ai_[2] = 0;
          _ai_[3] = 0;
          _ai_[4] = 0;
          _ai_[5] = 0;
          _ai_[10] = 0;
          _ai_[14] = 0;
          _ai_[9] = _ai_[6];
          _ai_[14] = _ai_[14] + 1 | 0;
          var _bT_=3,_bU_=0;
          if(_ai_[14] < _ai_[15])
           {var _bR_=[0,- _ai_[13] | 0,[3,_bU_,_bT_],0];
            _E_(_ai_,_bR_);
            _ai_[1] = [0,[0,_ai_[13],_bR_],_ai_[1]]}
          else
           if(_ai_[14] === _ai_[15])
            {var _bS_=_ai_[16],_bQ_=caml_ml_string_length(_bS_);
             _E_(_ai_,[0,_bQ_,[0,_bS_],_bQ_]);
             _P_(_ai_)}
          caml_call1(_ai_[18],0);
          break}}
      return caml_call1(_h_,0)};
    var
     _ak_=joo_global_object,
     _am_=undefined,
     _an_=_ak_.Array,
     _ap_=[248,_ao_,caml_fresh_oo_id(0)],
     _aq_=[0,_ap_,{}],
     _al_=null,
     _aj_=caml_obj_tag(_aq_) === 248?_aq_:_aq_[1];
    caml_register_named_value(caml_new_string("jsError"),_aj_);
    (function(exn){throw exn});
    var _ar_=_ak_.JSON;
    _z_
     (function(_bN_)
       {return _bN_[1] === _ap_?[0,caml_js_to_string(_bN_[2].toString())]:0});
    _z_
     (function(_bM_)
       {return _bM_ instanceof _an_?0:[0,caml_js_to_string(_bM_.toString())]});
    function _as_(_bL_,_bK_){_bL_.appendChild(_bK_);return 0}
    var _at_=_ak_.document;
    function _av_(_bJ_,_bI_){return _bJ_?caml_call1(_bI_,_bJ_[1]):0}
    function _aw_(_bH_,_bG_){return _bH_.createElement(_bG_.toString())}
    var _ax_=[0,785140586];
    function _ay_(_bs_,_br_,_bq_,_bp_)
     {for(;;)
       {if(0 === _bs_)if(0 === _br_)return _aw_(_bq_,_bp_);
        var _bt_=_ax_[1];
        if(785140586 === _bt_)
         {try
           {var
             _bw_=_at_.createElement('<input name="x">'),
             _bx_=_bw_.tagName.toLowerCase() === "input"?1:0,
             _by_=_bx_?_bw_.name === "x"?1:0:_bx_,
             _bu_=_by_}
          catch(_bF_){var _bu_=0}
          var _bv_=_bu_?982028505:-1003883683;
          _ax_[1] = _bv_;
          continue}
        if(982028505 <= _bt_)
         {var _bz_=new _an_();
          _bz_.push("<",_bp_.toString());
          _av_
           (_bs_,
            function(_bE_)
             {_bz_.push(' type="',caml_js_html_escape(_bE_),'"');return 0});
          _av_
           (_br_,
            function(_bD_)
             {_bz_.push(' name="',caml_js_html_escape(_bD_),'"');return 0});
          _bz_.push(">");
          return _bq_.createElement(_bz_.join(""))}
        var _bA_=_aw_(_bq_,_bp_);
        _av_(_bs_,function(_bC_){return _bA_.type = _bC_});
        _av_(_br_,function(_bB_){return _bA_.name = _bB_});
        return _bA_}}
    caml_fresh_oo_id(0);
    _ak_.HTMLElement === _am_;
    var _aA_=caml_js_get_console(0);
    function _aB_(_bo_){return _aA_.log(_bo_.toString())}
    var _aC_=chrome.storage.sync;
    function _aD_(_bn_,_bm_,_bl_)
     {return _bn_.setAttribute(_bm_.toString(),_bl_.toString())}
    function _aH_(_bk_){return _c_(_aJ_,_c_(_bk_,_aI_))}
    function _aK_(_be_)
     {var
       _bf_=
        _c_
         (_aO_,
          _c_
           (_r_
             (_aN_,
              _k_
               (function(_bi_)
                 {var _bj_=_c_(_aM_,_bi_[2]);return _c_(_aH_(_bi_[1]),_bj_)},
                _be_)),
            _aL_));
      try
       {var _bg_=_ar_.parse(_bf_.toString());return _bg_}
      catch(_bh_){_aB_(_c_(_aP_,_bf_));return {}}}
    var _au_=_at_.getElementById("buttonDiv");
    if(_au_ == _al_)throw Not_found;
    _l_
     (function(_aY_)
       {var _aZ_=_aK_([0,[0,_aR_,_aH_(_aY_)],0]);
        function _a0_(_bd_){return _aB_(_c_(_aS_,_aY_))}
        var
         _a1_=0,
         _a2_=0,
         _a3_=0,
         _a4_=
          [0,
           [0,
            [0,
             _aT_,
             function(_bc_)
              {var _bb_=[0,_a0_]?caml_js_wrap_callback(_a0_):_am_;
               _aC_.set(_aZ_,_bb_);
               return 1}],
            _a3_]],
         _a5_=[0,[0,[0,_aU_,_aY_],0]],
         _a6_=0,
         _aW_=_a5_?_a5_[1]:_a5_,
         _aX_=_a4_?_a4_[1]:_a4_,
         _aV_=_ay_(0,0,_at_,_az_);
        _l_(function(_ba_){return 0},_aX_);
        _l_(function(_a$_){return _aV_.classList.add(_a$_.toString())},_a6_);
        _aD_
         (_aV_,
          _aG_,
          _r_
           (_aF_,
            _k_
             (function(_a9_)
               {var _a__=_c_(_aE_,_a9_[2]);return _c_(_a9_[1],_a__)},
              _aW_)));
        _l_(function(_a8_){return _aD_(_aV_,_a8_[1],_a8_[2])},_a2_);
        _l_(function(_a7_){return _as_(_aV_,_a7_)},_a1_);
        return _as_(_au_,_aV_)},
      _aQ_);
    caml_call1(_g_[1],0);
    return}
  (function(){return this}()));
